version: '3'

services:
 
  kong:
    image: kong:2.0.3-centos
    environment:
      - KONG_LUA_SSL_VERIFY_DEPTH=3
      - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/plugin-development/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_LOG_LEVEL=debug
      - KONG_PLUGINS=bundled,${NAME}
      - KONG_NGINX_HTTP_LUA_SHARED_DICT=oauth_jwt_shared_dict 32m
      - KONG_NGINX_MAIN_ENV=KONG_OAUTH_JWT_PLUGIN_PUBLIC_KEYS
      - KONG_OAUTH_JWT_PLUGIN_PUBLIC_KEYS={"12345678-1234-1234-1234-123456789ABC":"LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzOUk3QndkZTdzV3hsRmdGdElhVQpiTDVBUjY2WWJ0MmJmazFqREFDYjd4b25mam54Sm5nZXdBSnZtTWxmYzBtV0owVll1TVJnalExUExsUUNqL0o3ClNZR1UydnNtS0I3VjIyVjU4Yjd6Z1BCVGtNNDFWYytOZks2M3dGVUdYbUQrdzdBSTFiOXRXZzhORXk3UkRyaW0KZldmUnhLNGlUSGZrSnpMYXJ6c3MzRHVzUzRNbTRJVXIzc2ZXNDFVZVhGRE1ubnc1RWRLbHdvd1lFT3RaaXJJbQpZU1QrZDE5QWFlaDVOMU94YldoVWxqci9NYnFXNXlWV2RPaEZqZENKeDJQZWgxdU9JUUlScjV0U0Rva2kzZ0FLClRWRnpyV3ZoZE51SGw1NTdKV2FTVnJxano5TGt0VEUyN3lKUlhtbGZmK1BSb0VhcmdGY0s1RnhzdDFlSnRkYTIKT1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="}
    volumes:
      - plugin-development:/plugin-development
    user: "0:0"
    command:
      - /bin/bash
      - -c
      - |
        mkdir -p /usr/local/lib/luarocks/rocks-5.1/${NAME}/${VERSION}/
        ln -s /plugin-development/${NAME}-${VERSION}.rockspec /usr/local/lib/luarocks/rocks-5.1/${NAME}/${VERSION}/${NAME}-${VERSION}.rockspec
        ln -s /plugin-development/src /usr/local/share/lua/5.1/kong/plugins/${NAME}
        kong start
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"

volumes:
  plugin-development:
    driver: local
    driver_opts:
       type: none
       o: bind
       device: ${PWD}/
